#!/bin/sh

export mirror='https://mirrors.tuna.tsinghua.edu.cn/alpine'
export arch='aarch64'
export release='edge'

err() {
	echo "$@" >&2
	exit 1
}

if [[ "$(id -u)" -ne 0 ]]; then
	err 'Please run as root'
fi

ensure() {  
	{ set +x; } 2>/dev/null
        [ $# -lt 1 ] && return 0
	$@ || err failed executing: "$@"
	set -x
}

if [ -z "$1" ]
then
	printf 'Specify path as the first argument\n' >&2
	exit 1
fi

ensure export rxrand="$(base64 < /dev/random | tr -d '/+=' | head -c 10)"

set -xu

ensure export chroot_dir="$1"
ensure mkdir -p "${chroot_dir}"

# DOWNLOAD APK AND BOOTSTRAP BASE SYSTEM
ensure mkdir "/tmp/alpine-chroot-tmp-$rxrand"
ensure cd "/tmp/alpine-chroot-tmp-$rxrand"
ensure curl -LO "${mirror}/${release}/main/${arch}/apk-tools-static-2.14.4-r1.apk"
ensure tar -xzf apk-tools-static-*.apk
ensure ./sbin/apk.static -X "${mirror}/${release}/main" -U --allow-untrusted -p "${chroot_dir}" --initdb add alpine-base
ensure cd "${chroot_dir}"
ensure rm -rf "/tmp/alpine-chroot-tmp-$rxrand"

# ADD REPOSITORIES TO APK
ensure cp -L /etc/resolv.conf ${chroot_dir}/etc/
ensure mkdir -p ${chroot_dir}/etc/apk
ensure echo "${mirror}/${release}/main" > ${chroot_dir}/etc/apk/repositories
ensure echo "${mirror}/${release}/community" >> ${chroot_dir}/etc/apk/repositories
if [ "${release}" = edge ]
then
	ensure echo "${mirror}/edge/testing" >> ${chroot_dir}/etc/apk/repositories
fi
