#!/bin/sh

err() {
	echo "$@" >&2
	exit 1
}

if [[ "$(id -u)" -ne 0 ]]; then
	err 'Please run as root'
fi

ensure() {  
	{ set +x; } 2>/dev/null
        [ $# -lt 1 ] && return 0
	$@ || err failed executing: "$@"
	set -x
}

set -xu

ensure export chroot_dir="$1"

umount "${chroot_dir}/dev"
umount "${chroot_dir}/proc"
umount "${chroot_dir}/sys"
ensure mount -o bind /dev "${chroot_dir}/dev"
ensure mount -t proc none "${chroot_dir}/proc"
ensure mount -o bind /sys "${chroot_dir}/sys"

{ set +x; } 2>/dev/null

printf '\n\nNow, type the following to enter the chroot:\n\n'
printf "chroot '%s' /bin/ash -l\n\n" "${chroot_dir}"
