#!/bin/sh

set -e

cd ~/misc

rq="$(dnf repoquery --qf '%{name}' 2>/dev/null)"

for v in "$@"
do
	if grep -q '^'"$v"'$' <<< "$rq"
	then
		printf '%s\n' "$v" >> fedora-packages.txt
	else
		printf 'Package %s not found\n' "$v" >&2;
		exit 1
	fi
done

xargs sudo dnf install < fedora-packages.txt 2>&1 | grep -v '^Package .* is already installed.'
