#!/bin/sh

# assume that package names don't contain spaces too

set -e

cd ~/misc

available="$(dnf repoquery --qf '%{name}' 2>/dev/null)"
adding=""

for v in "$@"
do
	if grep -q '^'"$v"'$' <<< "$available"
	then
		grep -q '^'"$v"'$' fedora-packages.txt || printf '%s\n' "$v" >> fedora-packages.txt
		adding="$adding $v"
	else
		printf 'Package %s not found\n' "$v" >&2;
		exit 1
	fi
done

git commit fedora-packages.txt -m "$adding"

userinstalled="$(dnf repoquery --userinstalled --qf '%{name}' 2>/dev/null)"
to_add=""

for pkg in $(cat fedora-packages.txt)
do
	grep -q '^'"$pkg"'$' <<< "$userinstalled" || to_add="$to_add $pkg"
done

sudo dnf install $(tr '\n' ' ' <<< "$to_add")
