#!/bin/sh

set -e

cd ~/misc

for v in "$@"
do
	if dnf repoquery --qf '%{name}' 2>/dev/null | grep -q '^'"$v"'$'
	then
		printf '%s\n' "$v" >> fedora-packages.txt
	else
		printf 'Package not found\n' >&2;
		exit 1
	fi
done

xargs sudo dnf install < fedora-packages.txt
